#ifndef PNP_FFI_H
#define PNP_FFI_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Error codes.
 */
typedef enum pnp_error_t {
    PNP_OK = 0,
    PNP_ERROR_INSUFFICIENT_POINTS = 1,
    PNP_ERROR_SOLVER_FAILED = 2,
    PNP_ERROR_MISMATCHED_COUNTS = 3,
    PNP_ERROR_NULL_POINTER = 4,
    PNP_ERROR_INVALID_STRING = 5,
} pnp_error_t;

/**
 * Solve method enum.
 */
typedef enum pnp_method_t {
    PNP_METHOD_EPNP = 0,
    PNP_METHOD_ITERATIVE = 1,
    PNP_METHOD_SQPNP = 2,
} pnp_method_t;

/**
 * 3D vector.
 */
typedef struct pnp_vector3_t {
    double x;
    double y;
    double z;
} pnp_vector3_t;

/**
 * Quaternion (Hamilton convention: x, y, z, w).
 */
typedef struct pnp_quaternion_t {
    double x;
    double y;
    double z;
    double w;
} pnp_quaternion_t;

/**
 * Pose (position + rotation).
 */
typedef struct pnp_pose_t {
    struct pnp_vector3_t position;
    struct pnp_quaternion_t rotation;
} pnp_pose_t;

/**
 * Result struct returned by square pose estimation.
 */
typedef struct pnp_square_pose_estimate_t {
    enum pnp_error_t error;
    struct pnp_pose_t pose;
    double confidence;
    double normalized_corner_error;
    double ray_distances[4];
} pnp_square_pose_estimate_t;

/**
 * 3D ray.
 */
typedef struct pnp_ray_t {
    struct pnp_vector3_t origin;
    struct pnp_vector3_t direction;
} pnp_ray_t;

/**
 * 2D vector.
 */
typedef struct pnp_vector2_t {
    double x;
    double y;
} pnp_vector2_t;

/**
 * Calibrated monocular camera (OpenCV intrinsics + optional distortion).
 *
 * `dist` may be null when `dist_len == 0`. Supported lengths: 0, 4, 5, 8
 * (OpenCV Brown–Conrady / rational order).
 */
typedef struct pnp_camera_t {
    double fx;
    double fy;
    double cx;
    double cy;
    const double *dist;
    uintptr_t dist_len;
} pnp_camera_t;

/**
 * Result struct returned by solve functions.
 */
typedef struct pnp_result_t {
    enum pnp_error_t error;
    struct pnp_pose_t pose;
} pnp_result_t;

/**
 * Landmark (3D point with string ID).
 */
typedef struct pnp_landmark_t {
    const char *id;
    struct pnp_vector3_t position;
} pnp_landmark_t;

/**
 * Landmark observation (2D point with string ID).
 */
typedef struct pnp_landmark_observation_t {
    const char *id;
    struct pnp_vector2_t position;
} pnp_landmark_observation_t;

/**
 * Per-landmark stereo observation (pixel coords, possibly distorted).
 *
 * `has_left` / `has_right`: non-zero = present; zero = missing (position ignored).
 */
typedef struct pnp_stereo_observation_t {
    const char *id;
    int32_t has_left;
    struct pnp_vector2_t left;
    int32_t has_right;
    struct pnp_vector2_t right;
} pnp_stereo_observation_t;

/**
 * Calibrated stereo pair: left/right monocular cameras + fixed extrinsics.
 *
 * `right_from_left` is the pose of the right camera in the left camera frame
 * (OpenCV convention for stereo math).
 */
typedef struct pnp_stereo_rig_t {
    struct pnp_camera_t left;
    struct pnp_camera_t right;
    struct pnp_pose_t right_from_left;
} pnp_stereo_rig_t;

/**
 * Options for multi-view monocular camera calibration.
 *
 * Matches `CalibrateOptions` in pnp-core. Defaults (when a null options
 * pointer is passed to the calibrate entry point):
 * `min_views = 3`, `fix_aspect_ratio = true`, `fix_principal_point = false`,
 * `dist_len = 5`, `max_iterations = 100`, `function_tolerance = 1e-10`,
 * `rms_success_threshold < 0` (disabled).
 *
 * `rms_success_threshold`: if `< 0` (or non-finite), no hard RMS failure;
 * otherwise fail when overall RMS exceeds this value.
 */
typedef struct pnp_calibrate_options_t {
    uintptr_t min_views;
    bool fix_aspect_ratio;
    bool fix_principal_point;
    uintptr_t dist_len;
    uintptr_t max_iterations;
    double function_tolerance;
    double rms_success_threshold;
} pnp_calibrate_options_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Estimate a planar square-marker pose from four corner rays.
 *
 * Rays must be ordered top-left, top-right, bottom-right, bottom-left.
 * Directions may be unnormalized. `physical_size` must use the same units as
 * the ray coordinate frame, normally meters in the AR calibration flow.
 *
 * # Safety
 * `rays` must point to exactly four valid `pnp_ray_t` structs.
 */
struct pnp_square_pose_estimate_t pnp_estimate_square_pose_from_rays(const struct pnp_ray_t *rays,
                                                                     uintptr_t num_rays,
                                                                     double physical_size);

/**
 * Estimate a planar square-marker pose from four corner image pixels and a camera.
 *
 * Pixels must be ordered top-left, top-right, bottom-right, bottom-left.
 *
 * # Safety
 * `pixels` must point to exactly four valid `pnp_vector2_t` values when
 * `num_pixels == 4`. `camera` must be a valid pointer; see `pnp_camera_t`.
 */
struct pnp_square_pose_estimate_t pnp_estimate_square_pose_from_pixels(const struct pnp_vector2_t *pixels,
                                                                       uintptr_t num_pixels,
                                                                       double physical_size,
                                                                       const struct pnp_camera_t *camera);

/**
 * Solve PnP and return object pose in OpenGL coordinates.
 *
 * # Safety
 * `landmarks` must point to `num_landmarks` valid `pnp_landmark_t` structs.
 * `observations` must point to `num_observations` valid `pnp_landmark_observation_t` structs.
 * All `id` pointers within landmarks/observations must be valid null-terminated C strings.
 * `camera` must be valid; if `dist_len > 0`, `dist` must point to that many doubles.
 */
struct pnp_result_t pnp_solve(const struct pnp_landmark_t *landmarks,
                              uintptr_t num_landmarks,
                              const struct pnp_landmark_observation_t *observations,
                              uintptr_t num_observations,
                              const struct pnp_camera_t *camera,
                              enum pnp_method_t method);

/**
 * Solve PnP and return camera pose (inverted).
 *
 * # Safety
 * Same requirements as `pnp_solve`.
 */
struct pnp_result_t pnp_solve_camera_pose(const struct pnp_landmark_t *landmarks,
                                          uintptr_t num_landmarks,
                                          const struct pnp_landmark_observation_t *observations,
                                          uintptr_t num_observations,
                                          const struct pnp_camera_t *camera,
                                          enum pnp_method_t method);

/**
 * Invert a solvePnP pose to get the camera pose.
 *
 * # Safety
 * `pose` may be null (returns identity). If non-null, it must point to a valid
 * `pnp_pose_t`.
 */
struct pnp_pose_t pnp_camera_pose_from_solve_pnp_pose(const struct pnp_pose_t *pose);

/**
 * Solve stereo PnP and return object pose in OpenGL coordinates (left primary).
 *
 * Landmarks and observations are matched by string `id` (same length required).
 * Missing left/right pixels (`has_* == 0`) are skipped in the joint residual.
 *
 * # Safety
 * `landmarks` must point to `num_landmarks` valid `pnp_landmark_t` structs.
 * `observations` must point to `num_observations` valid `pnp_stereo_observation_t`
 * structs. All `id` pointers must be valid null-terminated C strings.
 * `rig` must be valid; camera `dist` buffers follow `pnp_camera_t` rules.
 */
struct pnp_result_t pnp_solve_stereo(const struct pnp_landmark_t *landmarks,
                                     uintptr_t num_landmarks,
                                     const struct pnp_stereo_observation_t *observations,
                                     uintptr_t num_observations,
                                     const struct pnp_stereo_rig_t *rig,
                                     enum pnp_method_t method);

/**
 * Calibrate monocular intrinsics from multi-view square-marker corners.
 *
 * `corners` is a flat array of `num_views * 4` image points. Each view is four
 * corners in **TL → TR → BR → BL** order (same as square pose estimation).
 * `physical_size` is the square side length in the same units used for object
 * points (typically meters).
 *
 * `options` may be null to use defaults (`min_views=3`, `fix_aspect_ratio=true`,
 * `dist_len=5`, …). See [`pnp_calibrate_options_t`].
 *
 * # Output buffers (caller-owned)
 *
 * - `out_camera`: on entry, if distortion will be estimated (`dist_len > 0`),
 *   set `out_camera.dist` to a writable buffer and `out_camera.dist_len` to its
 *   capacity (at least the requested `dist_len`, max 8). On success fills
 *   `fx/fy/cx/cy`, writes coefficients into `dist`, and sets `dist_len` to the
 *   actual count (0 when pinhole). For pinhole (`dist_len=0`) `dist` may be null.
 * - `out_rms`: overall RMS reprojection error in pixels.
 * - `out_per_view_rms`: capacity ≥ `num_views`; first `*out_views_used` filled.
 * - `out_poses`: capacity ≥ `num_views`; first `*out_views_used` OpenGL object
 *   poses (same convention as `pnp_solve`).
 * - `out_views_used`: number of views that contributed to the solution.
 *
 * There is no fixed max-views limit; allocate per-view buffers for `num_views`.
 *
 * # Safety
 * `corners` must point to `num_views * 4` valid `pnp_vector2_t` when
 * `num_views > 0`. All non-optional out pointers must be valid and writable.
 * Output per-view buffers must have capacity ≥ `num_views`.
 */
enum pnp_error_t pnp_calibrate_from_square_views(const struct pnp_vector2_t *corners,
                                                 uintptr_t num_views,
                                                 double physical_size,
                                                 uint32_t image_width,
                                                 uint32_t image_height,
                                                 const struct pnp_calibrate_options_t *options,
                                                 struct pnp_camera_t *out_camera,
                                                 double *out_rms,
                                                 double *out_per_view_rms,
                                                 struct pnp_pose_t *out_poses,
                                                 uintptr_t *out_views_used);

/**
 * Midpoint-triangulate a stereo correspondence into the left OpenCV frame.
 *
 * On success writes the 3D point to `out_point` and returns `PNP_OK` in
 * `pnp_result_t.error` (the `pose` field is zeroed / unused).
 *
 * # Safety
 * `rig` must be a valid pointer; camera `dist` buffers follow `pnp_camera_t`.
 * `out_point` must be a valid writable pointer.
 */
struct pnp_result_t pnp_triangulate(struct pnp_vector2_t left,
                                    struct pnp_vector2_t right,
                                    const struct pnp_stereo_rig_t *rig,
                                    struct pnp_vector3_t *out_point);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PNP_FFI_H */
