[package]
name = "pnplab-python"
description = "Python and NumPy bindings for PnPLab"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[lib]
name = "_native"
crate-type = ["cdylib", "rlib"]
test = false
doctest = false

[dependencies]
numpy = "0.29.0"
pnp-core = { path = "../../crates/pnp-core" }
pyo3 = "0.29.0"
