#ifndef PEYOTE_PNP_FFI_H
#define PEYOTE_PNP_FFI_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Error codes.
 */
typedef enum pnp_error_t {
    PNP_OK = 0,
    PNP_ERROR_INSUFFICIENT_POINTS = 1,
    PNP_ERROR_SOLVER_FAILED = 2,
    PNP_ERROR_MISMATCHED_COUNTS = 3,
    PNP_ERROR_NULL_POINTER = 4,
    PNP_ERROR_INVALID_STRING = 5,
} pnp_error_t;

/**
 * Solve method enum.
 */
typedef enum pnp_method_t {
    PNP_METHOD_EPNP = 0,
    PNP_METHOD_ITERATIVE = 1,
    PNP_METHOD_SQPNP = 2,
} pnp_method_t;

/**
 * 3D vector.
 */
typedef struct pnp_vector3_t {
    double x;
    double y;
    double z;
} pnp_vector3_t;

/**
 * Quaternion (Hamilton convention: x, y, z, w).
 */
typedef struct pnp_quaternion_t {
    double x;
    double y;
    double z;
    double w;
} pnp_quaternion_t;

/**
 * Pose (position + rotation).
 */
typedef struct pnp_pose_t {
    struct pnp_vector3_t position;
    struct pnp_quaternion_t rotation;
} pnp_pose_t;

/**
 * Result struct returned by square pose estimation.
 */
typedef struct pnp_square_pose_estimate_t {
    enum pnp_error_t error;
    struct pnp_pose_t pose;
    double confidence;
    double normalized_corner_error;
    double ray_distances[4];
} pnp_square_pose_estimate_t;

/**
 * 3D ray.
 */
typedef struct pnp_ray_t {
    struct pnp_vector3_t origin;
    struct pnp_vector3_t direction;
} pnp_ray_t;

/**
 * 2D vector.
 */
typedef struct pnp_vector2_t {
    double x;
    double y;
} pnp_vector2_t;

/**
 * Calibrated monocular camera (OpenCV intrinsics + optional distortion).
 *
 * `dist` may be null when `dist_len == 0`. Supported lengths: 0, 4, 5, 8
 * (OpenCV Brown–Conrady / rational order).
 */
typedef struct pnp_camera_t {
    double fx;
    double fy;
    double cx;
    double cy;
    const double *dist;
    uintptr_t dist_len;
} pnp_camera_t;

/**
 * Result struct returned by solve functions.
 */
typedef struct pnp_result_t {
    enum pnp_error_t error;
    struct pnp_pose_t pose;
} pnp_result_t;

/**
 * Landmark (3D point with string ID).
 */
typedef struct pnp_landmark_t {
    const char *id;
    struct pnp_vector3_t position;
} pnp_landmark_t;

/**
 * Landmark observation (2D point with string ID).
 */
typedef struct pnp_landmark_observation_t {
    const char *id;
    struct pnp_vector2_t position;
} pnp_landmark_observation_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Estimate a planar square-marker pose from four corner rays.
 *
 * Rays must be ordered top-left, top-right, bottom-right, bottom-left.
 * Directions may be unnormalized. `physical_size` must use the same units as
 * the ray coordinate frame, normally meters in the AR calibration flow.
 *
 * # Safety
 * `rays` must point to exactly four valid `pnp_ray_t` structs.
 */
struct pnp_square_pose_estimate_t peyote_pnp_estimate_square_pose_from_rays(const struct pnp_ray_t *rays,
                                                                            uintptr_t num_rays,
                                                                            double physical_size);

/**
 * Estimate a planar square-marker pose from four corner image pixels and a camera.
 *
 * Pixels must be ordered top-left, top-right, bottom-right, bottom-left.
 *
 * # Safety
 * `pixels` must point to exactly four valid `pnp_vector2_t` values when
 * `num_pixels == 4`. `camera` must be a valid pointer; see `pnp_camera_t`.
 */
struct pnp_square_pose_estimate_t peyote_pnp_estimate_square_pose_from_pixels(const struct pnp_vector2_t *pixels,
                                                                              uintptr_t num_pixels,
                                                                              double physical_size,
                                                                              const struct pnp_camera_t *camera);

/**
 * Solve PnP and return object pose in OpenGL coordinates.
 *
 * # Safety
 * `landmarks` must point to `num_landmarks` valid `pnp_landmark_t` structs.
 * `observations` must point to `num_observations` valid `pnp_landmark_observation_t` structs.
 * All `id` pointers within landmarks/observations must be valid null-terminated C strings.
 * `camera` must be valid; if `dist_len > 0`, `dist` must point to that many doubles.
 */
struct pnp_result_t peyote_pnp_solve(const struct pnp_landmark_t *landmarks,
                                     uintptr_t num_landmarks,
                                     const struct pnp_landmark_observation_t *observations,
                                     uintptr_t num_observations,
                                     const struct pnp_camera_t *camera,
                                     enum pnp_method_t method);

/**
 * Solve PnP and return camera pose (inverted).
 *
 * # Safety
 * Same requirements as `peyote_pnp_solve`.
 */
struct pnp_result_t peyote_pnp_solve_camera_pose(const struct pnp_landmark_t *landmarks,
                                                 uintptr_t num_landmarks,
                                                 const struct pnp_landmark_observation_t *observations,
                                                 uintptr_t num_observations,
                                                 const struct pnp_camera_t *camera,
                                                 enum pnp_method_t method);

/**
 * Invert a solvePnP pose to get the camera pose.
 */
struct pnp_pose_t peyote_pnp_camera_pose_from_solve_pnp_pose(const struct pnp_pose_t *pose);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PEYOTE_PNP_FFI_H */
