// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[allow(dead_code, clippy::all)]
pub mod auki {
    pub mod pnp {

        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() =
                super::super::super::__link_custom_section_describing_imports;

            use super::super::super::_rt;
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct Vector2 {
                pub x: f64,
                pub y: f64,
            }
            impl ::core::fmt::Debug for Vector2 {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    f.debug_struct("Vector2")
                        .field("x", &self.x)
                        .field("y", &self.y)
                        .finish()
                }
            }
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct Vector3 {
                pub x: f64,
                pub y: f64,
                pub z: f64,
            }
            impl ::core::fmt::Debug for Vector3 {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    f.debug_struct("Vector3")
                        .field("x", &self.x)
                        .field("y", &self.y)
                        .field("z", &self.z)
                        .finish()
                }
            }
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct Quaternion {
                pub x: f64,
                pub y: f64,
                pub z: f64,
                pub w: f64,
            }
            impl ::core::fmt::Debug for Quaternion {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    f.debug_struct("Quaternion")
                        .field("x", &self.x)
                        .field("y", &self.y)
                        .field("z", &self.z)
                        .field("w", &self.w)
                        .finish()
                }
            }
            /// Calibrated monocular camera. `dist` is OpenCV-ordered coeffs (empty = pinhole).
            #[derive(Clone)]
            pub struct Camera {
                pub fx: f64,
                pub fy: f64,
                pub cx: f64,
                pub cy: f64,
                pub dist: _rt::Vec<f64>,
            }
            impl ::core::fmt::Debug for Camera {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    f.debug_struct("Camera")
                        .field("fx", &self.fx)
                        .field("fy", &self.fy)
                        .field("cx", &self.cx)
                        .field("cy", &self.cy)
                        .field("dist", &self.dist)
                        .finish()
                }
            }
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct Pose {
                pub position: Vector3,
                pub rotation: Quaternion,
            }
            impl ::core::fmt::Debug for Pose {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    f.debug_struct("Pose")
                        .field("position", &self.position)
                        .field("rotation", &self.rotation)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct SquarePoseEstimate {
                pub pose: Pose,
                pub confidence: f64,
                pub normalized_corner_error: f64,
                pub ray_distances: _rt::Vec<f64>,
            }
            impl ::core::fmt::Debug for SquarePoseEstimate {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    f.debug_struct("SquarePoseEstimate")
                        .field("pose", &self.pose)
                        .field("confidence", &self.confidence)
                        .field("normalized-corner-error", &self.normalized_corner_error)
                        .field("ray-distances", &self.ray_distances)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct Landmark {
                pub id: _rt::String,
                pub position: Vector3,
            }
            impl ::core::fmt::Debug for Landmark {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    f.debug_struct("Landmark")
                        .field("id", &self.id)
                        .field("position", &self.position)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct LandmarkObservation {
                pub id: _rt::String,
                pub position: Vector2,
            }
            impl ::core::fmt::Debug for LandmarkObservation {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    f.debug_struct("LandmarkObservation")
                        .field("id", &self.id)
                        .field("position", &self.position)
                        .finish()
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum SolvePnpMethod {
                Epnp,
                Iterative,
                Sqpnp,
            }
            impl ::core::fmt::Debug for SolvePnpMethod {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    match self {
                        SolvePnpMethod::Epnp => f.debug_tuple("SolvePnpMethod::Epnp").finish(),
                        SolvePnpMethod::Iterative => {
                            f.debug_tuple("SolvePnpMethod::Iterative").finish()
                        }
                        SolvePnpMethod::Sqpnp => f.debug_tuple("SolvePnpMethod::Sqpnp").finish(),
                    }
                }
            }

            impl SolvePnpMethod {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> SolvePnpMethod {
                    if !cfg!(debug_assertions) {
                        return unsafe { ::core::mem::transmute(val) };
                    }

                    match val {
                        0 => SolvePnpMethod::Epnp,
                        1 => SolvePnpMethod::Iterative,
                        2 => SolvePnpMethod::Sqpnp,

                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }

            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum PnpError {
                InsufficientPoints,
                SolverFailed,
                MismatchedCounts,
            }
            impl PnpError {
                pub fn name(&self) -> &'static str {
                    match self {
                        PnpError::InsufficientPoints => "insufficient-points",
                        PnpError::SolverFailed => "solver-failed",
                        PnpError::MismatchedCounts => "mismatched-counts",
                    }
                }
                pub fn message(&self) -> &'static str {
                    match self {
                        PnpError::InsufficientPoints => "",
                        PnpError::SolverFailed => "",
                        PnpError::MismatchedCounts => "",
                    }
                }
            }
            impl ::core::fmt::Debug for PnpError {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    f.debug_struct("PnpError")
                        .field("code", &(*self as i32))
                        .field("name", &self.name())
                        .field("message", &self.message())
                        .finish()
                }
            }
            impl ::core::fmt::Display for PnpError {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    write!(f, "{} (error {})", self.name(), *self as i32)
                }
            }

            impl ::core::error::Error for PnpError {}

            impl PnpError {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> PnpError {
                    if !cfg!(debug_assertions) {
                        return unsafe { ::core::mem::transmute(val) };
                    }

                    match val {
                        0 => PnpError::InsufficientPoints,
                        1 => PnpError::SolverFailed,
                        2 => PnpError::MismatchedCounts,

                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
        }
    }
}
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod auki {
        pub mod pnp {

            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod solver {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() =
                    super::super::super::super::__link_custom_section_describing_imports;

                use super::super::super::super::_rt;
                pub type Landmark = super::super::super::super::auki::pnp::types::Landmark;
                pub type LandmarkObservation =
                    super::super::super::super::auki::pnp::types::LandmarkObservation;
                pub type Camera = super::super::super::super::auki::pnp::types::Camera;
                pub type Pose = super::super::super::super::auki::pnp::types::Pose;
                pub type SolvePnpMethod =
                    super::super::super::super::auki::pnp::types::SolvePnpMethod;
                pub type PnpError = super::super::super::super::auki::pnp::types::PnpError;
                pub type Vector2 = super::super::super::super::auki::pnp::types::Vector2;
                pub type SquarePoseEstimate =
                    super::super::super::super::auki::pnp::types::SquarePoseEstimate;
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_solve_pnp_cabi<T_: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: f64,
                    arg5: f64,
                    arg6: f64,
                    arg7: f64,
                    arg8: *mut u8,
                    arg9: usize,
                    arg10: i32,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result14 = {
                            let base6 = arg0;
                            let len6 = arg1;
                            let mut result6 = _rt::Vec::with_capacity(len6);
                            for i in 0..len6 {
                                let base =
                                    base6.add(i * (24 + 2 * ::core::mem::size_of::<*const u8>()));
                                let e6 = {
                                    let l0 = *base.add(0).cast::<*mut u8>();
                                    let l1 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let len2 = l1;
                                    let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);
                                    let l3 = *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<f64>();
                                    let l4 = *base
                                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<f64>();
                                    let l5 = *base
                                        .add(16 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<f64>();

                                    super::super::super::super::auki::pnp::types::Landmark {
                                        id: _rt::string_lift(bytes2),
                                        position:
                                            super::super::super::super::auki::pnp::types::Vector3 {
                                                x: l3,
                                                y: l4,
                                                z: l5,
                                            },
                                    }
                                };
                                result6.push(e6);
                            }
                            _rt::cabi_dealloc(
                                base6,
                                len6 * (24 + 2 * ::core::mem::size_of::<*const u8>()),
                                8,
                            );
                            let base12 = arg2;
                            let len12 = arg3;
                            let mut result12 = _rt::Vec::with_capacity(len12);
                            for i in 0..len12 {
                                let base =
                                    base12.add(i * (16 + 2 * ::core::mem::size_of::<*const u8>()));
                                let e12 = {
                                    let l7 = *base.add(0).cast::<*mut u8>();
                                    let l8 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let len9 = l8;
                                    let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);
                                    let l10 = *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<f64>();
                                    let l11 = *base
                                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<f64>();

                                    super::super::super::super::auki::pnp::types::LandmarkObservation{
                id: _rt::string_lift(bytes9),
                position: super::super::super::super::auki::pnp::types::Vector2{
                  x: l10,
                  y: l11,
                },
              }
                                };
                                result12.push(e12);
                            }
                            _rt::cabi_dealloc(
                                base12,
                                len12 * (16 + 2 * ::core::mem::size_of::<*const u8>()),
                                8,
                            );
                            let len13 = arg9;
                            T_::solve_pnp(
                                result6,
                                result12,
                                super::super::super::super::auki::pnp::types::Camera {
                                    fx: arg4,
                                    fy: arg5,
                                    cx: arg6,
                                    cy: arg7,
                                    dist: <_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(
                                        arg8.cast(),
                                        len13,
                                        len13,
                                    )),
                                },
                                super::super::super::super::auki::pnp::types::SolvePnpMethod::_lift(
                                    arg10 as u8,
                                ),
                            )
                        };
                        let ptr15 = (&raw mut _RET_AREA.0).cast::<u8>();
                        match result14 {
                            Ok(e) => {
                                *ptr15.add(0).cast::<u8>() = (0i32) as u8;
                                let super::super::super::super::auki::pnp::types::Pose {
                                    position: position16,
                                    rotation: rotation16,
                                } = e;
                                let super::super::super::super::auki::pnp::types::Vector3 {
                                    x: x17,
                                    y: y17,
                                    z: z17,
                                } = position16;
                                *ptr15.add(8).cast::<f64>() = _rt::as_f64(x17);
                                *ptr15.add(16).cast::<f64>() = _rt::as_f64(y17);
                                *ptr15.add(24).cast::<f64>() = _rt::as_f64(z17);
                                let super::super::super::super::auki::pnp::types::Quaternion {
                                    x: x18,
                                    y: y18,
                                    z: z18,
                                    w: w18,
                                } = rotation16;
                                *ptr15.add(32).cast::<f64>() = _rt::as_f64(x18);
                                *ptr15.add(40).cast::<f64>() = _rt::as_f64(y18);
                                *ptr15.add(48).cast::<f64>() = _rt::as_f64(z18);
                                *ptr15.add(56).cast::<f64>() = _rt::as_f64(w18);
                            }
                            Err(e) => {
                                *ptr15.add(0).cast::<u8>() = (1i32) as u8;
                                *ptr15.add(8).cast::<u8>() = (e.clone() as i32) as u8;
                            }
                        };
                        ptr15
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_solve_pnp_camera_pose_cabi<T_: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: f64,
                    arg5: f64,
                    arg6: f64,
                    arg7: f64,
                    arg8: *mut u8,
                    arg9: usize,
                    arg10: i32,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result14 = {
                            let base6 = arg0;
                            let len6 = arg1;
                            let mut result6 = _rt::Vec::with_capacity(len6);
                            for i in 0..len6 {
                                let base =
                                    base6.add(i * (24 + 2 * ::core::mem::size_of::<*const u8>()));
                                let e6 = {
                                    let l0 = *base.add(0).cast::<*mut u8>();
                                    let l1 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let len2 = l1;
                                    let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);
                                    let l3 = *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<f64>();
                                    let l4 = *base
                                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<f64>();
                                    let l5 = *base
                                        .add(16 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<f64>();

                                    super::super::super::super::auki::pnp::types::Landmark {
                                        id: _rt::string_lift(bytes2),
                                        position:
                                            super::super::super::super::auki::pnp::types::Vector3 {
                                                x: l3,
                                                y: l4,
                                                z: l5,
                                            },
                                    }
                                };
                                result6.push(e6);
                            }
                            _rt::cabi_dealloc(
                                base6,
                                len6 * (24 + 2 * ::core::mem::size_of::<*const u8>()),
                                8,
                            );
                            let base12 = arg2;
                            let len12 = arg3;
                            let mut result12 = _rt::Vec::with_capacity(len12);
                            for i in 0..len12 {
                                let base =
                                    base12.add(i * (16 + 2 * ::core::mem::size_of::<*const u8>()));
                                let e12 = {
                                    let l7 = *base.add(0).cast::<*mut u8>();
                                    let l8 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let len9 = l8;
                                    let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);
                                    let l10 = *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<f64>();
                                    let l11 = *base
                                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<f64>();

                                    super::super::super::super::auki::pnp::types::LandmarkObservation{
              id: _rt::string_lift(bytes9),
              position: super::super::super::super::auki::pnp::types::Vector2{
                x: l10,
                y: l11,
              },
            }
                                };
                                result12.push(e12);
                            }
                            _rt::cabi_dealloc(
                                base12,
                                len12 * (16 + 2 * ::core::mem::size_of::<*const u8>()),
                                8,
                            );
                            let len13 = arg9;
                            T_::solve_pnp_camera_pose(
                                result6,
                                result12,
                                super::super::super::super::auki::pnp::types::Camera {
                                    fx: arg4,
                                    fy: arg5,
                                    cx: arg6,
                                    cy: arg7,
                                    dist: <_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(
                                        arg8.cast(),
                                        len13,
                                        len13,
                                    )),
                                },
                                super::super::super::super::auki::pnp::types::SolvePnpMethod::_lift(
                                    arg10 as u8,
                                ),
                            )
                        };
                        let ptr15 = (&raw mut _RET_AREA.0).cast::<u8>();
                        match result14 {
                            Ok(e) => {
                                *ptr15.add(0).cast::<u8>() = (0i32) as u8;
                                let super::super::super::super::auki::pnp::types::Pose {
                                    position: position16,
                                    rotation: rotation16,
                                } = e;
                                let super::super::super::super::auki::pnp::types::Vector3 {
                                    x: x17,
                                    y: y17,
                                    z: z17,
                                } = position16;
                                *ptr15.add(8).cast::<f64>() = _rt::as_f64(x17);
                                *ptr15.add(16).cast::<f64>() = _rt::as_f64(y17);
                                *ptr15.add(24).cast::<f64>() = _rt::as_f64(z17);
                                let super::super::super::super::auki::pnp::types::Quaternion {
                                    x: x18,
                                    y: y18,
                                    z: z18,
                                    w: w18,
                                } = rotation16;
                                *ptr15.add(32).cast::<f64>() = _rt::as_f64(x18);
                                *ptr15.add(40).cast::<f64>() = _rt::as_f64(y18);
                                *ptr15.add(48).cast::<f64>() = _rt::as_f64(z18);
                                *ptr15.add(56).cast::<f64>() = _rt::as_f64(w18);
                            }
                            Err(e) => {
                                *ptr15.add(0).cast::<u8>() = (1i32) as u8;
                                *ptr15.add(8).cast::<u8>() = (e.clone() as i32) as u8;
                            }
                        };
                        ptr15
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_camera_pose_from_solve_pnp_pose_cabi<T_: Guest>(
                    arg0: f64,
                    arg1: f64,
                    arg2: f64,
                    arg3: f64,
                    arg4: f64,
                    arg5: f64,
                    arg6: f64,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result0 = {
                            T_::camera_pose_from_solve_pnp_pose(
                                super::super::super::super::auki::pnp::types::Pose {
                                    position:
                                        super::super::super::super::auki::pnp::types::Vector3 {
                                            x: arg0,
                                            y: arg1,
                                            z: arg2,
                                        },
                                    rotation:
                                        super::super::super::super::auki::pnp::types::Quaternion {
                                            x: arg3,
                                            y: arg4,
                                            z: arg5,
                                            w: arg6,
                                        },
                                },
                            )
                        };
                        let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                        let super::super::super::super::auki::pnp::types::Pose {
                            position: position2,
                            rotation: rotation2,
                        } = result0;
                        let super::super::super::super::auki::pnp::types::Vector3 {
                            x: x3,
                            y: y3,
                            z: z3,
                        } = position2;
                        *ptr1.add(0).cast::<f64>() = _rt::as_f64(x3);
                        *ptr1.add(8).cast::<f64>() = _rt::as_f64(y3);
                        *ptr1.add(16).cast::<f64>() = _rt::as_f64(z3);
                        let super::super::super::super::auki::pnp::types::Quaternion {
                            x: x4,
                            y: y4,
                            z: z4,
                            w: w4,
                        } = rotation2;
                        *ptr1.add(24).cast::<f64>() = _rt::as_f64(x4);
                        *ptr1.add(32).cast::<f64>() = _rt::as_f64(y4);
                        *ptr1.add(40).cast::<f64>() = _rt::as_f64(z4);
                        *ptr1.add(48).cast::<f64>() = _rt::as_f64(w4);
                        ptr1
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_estimate_square_pose_from_pixels_cabi<T_: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: f64,
                    arg3: f64,
                    arg4: f64,
                    arg5: f64,
                    arg6: f64,
                    arg7: *mut u8,
                    arg8: usize,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result2 =
                            {
                                let len0 = arg1;
                                let len1 = arg8;
                                T_::estimate_square_pose_from_pixels(
                                    <_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(
                                        arg0.cast(),
                                        len0,
                                        len0,
                                    )),
                                    arg2,
                                    super::super::super::super::auki::pnp::types::Camera {
                                        fx: arg3,
                                        fy: arg4,
                                        cx: arg5,
                                        cy: arg6,
                                        dist: <_ as From<_rt::Vec<_>>>::from(
                                            _rt::Vec::from_raw_parts(arg7.cast(), len1, len1),
                                        ),
                                    },
                                )
                            };
                        let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                        match result2 {
                            Ok(e) => {
                                *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                                let super::super::super::super::auki::pnp::types::SquarePoseEstimate{ pose:pose4, confidence:confidence4, normalized_corner_error:normalized_corner_error4, ray_distances:ray_distances4, } = e;
                                let super::super::super::super::auki::pnp::types::Pose {
                                    position: position5,
                                    rotation: rotation5,
                                } = pose4;
                                let super::super::super::super::auki::pnp::types::Vector3 {
                                    x: x6,
                                    y: y6,
                                    z: z6,
                                } = position5;
                                *ptr3.add(8).cast::<f64>() = _rt::as_f64(x6);
                                *ptr3.add(16).cast::<f64>() = _rt::as_f64(y6);
                                *ptr3.add(24).cast::<f64>() = _rt::as_f64(z6);
                                let super::super::super::super::auki::pnp::types::Quaternion {
                                    x: x7,
                                    y: y7,
                                    z: z7,
                                    w: w7,
                                } = rotation5;
                                *ptr3.add(32).cast::<f64>() = _rt::as_f64(x7);
                                *ptr3.add(40).cast::<f64>() = _rt::as_f64(y7);
                                *ptr3.add(48).cast::<f64>() = _rt::as_f64(z7);
                                *ptr3.add(56).cast::<f64>() = _rt::as_f64(w7);
                                *ptr3.add(64).cast::<f64>() = _rt::as_f64(confidence4);
                                *ptr3.add(72).cast::<f64>() = _rt::as_f64(normalized_corner_error4);
                                let vec8 = <_ as Into<_rt::Vec<_>>>::into(ray_distances4)
                                    .into_boxed_slice();
                                let ptr8 = vec8.as_ptr().cast::<u8>();
                                let len8 = vec8.len();
                                ::core::mem::forget(vec8);
                                *ptr3
                                    .add(80 + 1 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>() = len8;
                                *ptr3.add(80).cast::<*mut u8>() = ptr8.cast_mut();
                            }
                            Err(e) => {
                                *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                                *ptr3.add(8).cast::<u8>() = (e.clone() as i32) as u8;
                            }
                        };
                        ptr3
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_estimate_square_pose_from_pixels<T_: Guest>(
                    arg0: *mut u8,
                ) {
                    unsafe {
                        let l0 = i32::from(*arg0.add(0).cast::<u8>());
                        match l0 {
                            0 => {
                                let l1 = *arg0.add(80).cast::<*mut u8>();
                                let l2 = *arg0
                                    .add(80 + 1 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let base3 = l1;
                                let len3 = l2;
                                _rt::cabi_dealloc(base3, len3 * 8, 8);
                            }
                            _ => (),
                        }
                    }
                }
                pub trait Guest {
                    #[allow(async_fn_in_trait)]
                    fn solve_pnp(
                        landmarks: _rt::Vec<Landmark>,
                        observations: _rt::Vec<LandmarkObservation>,
                        camera: Camera,
                        method: SolvePnpMethod,
                    ) -> Result<Pose, PnpError>;
                    #[allow(async_fn_in_trait)]
                    fn solve_pnp_camera_pose(
                        landmarks: _rt::Vec<Landmark>,
                        observations: _rt::Vec<LandmarkObservation>,
                        camera: Camera,
                        method: SolvePnpMethod,
                    ) -> Result<Pose, PnpError>;
                    #[allow(async_fn_in_trait)]
                    fn camera_pose_from_solve_pnp_pose(pose: Pose) -> Pose;
                    #[allow(async_fn_in_trait)]
                    fn estimate_square_pose_from_pixels(
                        pixels: _rt::Vec<Vector2>,
                        physical_size: f64,
                        camera: Camera,
                    ) -> Result<SquarePoseEstimate, PnpError>;
                }
                #[doc(hidden)]

                macro_rules! __export_auki_pnp_solver_0_2_0_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[unsafe(export_name = "auki:pnp/solver@0.2.0#solve-pnp")]
    unsafe extern "C" fn export_solve_pnp(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,arg4: f64,arg5: f64,arg6: f64,arg7: f64,arg8: *mut u8,arg9: usize,arg10: i32,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_solve_pnp_cabi::<$ty>(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) }
    }
    #[unsafe(export_name = "auki:pnp/solver@0.2.0#solve-pnp-camera-pose")]
    unsafe extern "C" fn export_solve_pnp_camera_pose(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,arg4: f64,arg5: f64,arg6: f64,arg7: f64,arg8: *mut u8,arg9: usize,arg10: i32,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_solve_pnp_camera_pose_cabi::<$ty>(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) }
    }
    #[unsafe(export_name = "auki:pnp/solver@0.2.0#camera-pose-from-solve-pnp-pose")]
    unsafe extern "C" fn export_camera_pose_from_solve_pnp_pose(arg0: f64,arg1: f64,arg2: f64,arg3: f64,arg4: f64,arg5: f64,arg6: f64,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_camera_pose_from_solve_pnp_pose_cabi::<$ty>(arg0, arg1, arg2, arg3, arg4, arg5, arg6) }
    }
    #[unsafe(export_name = "auki:pnp/solver@0.2.0#estimate-square-pose-from-pixels")]
    unsafe extern "C" fn export_estimate_square_pose_from_pixels(arg0: *mut u8,arg1: usize,arg2: f64,arg3: f64,arg4: f64,arg5: f64,arg6: f64,arg7: *mut u8,arg8: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_estimate_square_pose_from_pixels_cabi::<$ty>(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) }
    }
    #[unsafe(export_name = "cabi_post_auki:pnp/solver@0.2.0#estimate-square-pose-from-pixels")]
    unsafe extern "C" fn _post_return_estimate_square_pose_from_pixels(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_estimate_square_pose_from_pixels::<$ty>(arg0) }
    }
  };);
}
                #[doc(hidden)]
                pub(crate) use __export_auki_pnp_solver_0_2_0_cabi;

                #[repr(align(8))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<u8>; 80 + 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit();
                        80 + 2 * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
mod _rt {
    #![allow(dead_code, unused_imports, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;

    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            unsafe { String::from_utf8_unchecked(bytes) }
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        unsafe {
            let layout = alloc::Layout::from_size_align_unchecked(size, align);
            alloc::dealloc(ptr, layout);
        }
    }

    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }

    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }

    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }

    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_pnp_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::auki::pnp::solver::__export_auki_pnp_solver_0_2_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::auki::pnp::solver);
  )
}
#[doc(inline)]
pub(crate) use __export_pnp_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.57.1:auki:pnp@0.2.0:pnp:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1234] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xd8\x08\x01A\x02\x01\
A\x0c\x01B\x17\x01r\x02\x01xu\x01yu\x04\0\x07vector2\x03\0\0\x01r\x03\x01xu\x01y\
u\x01zu\x04\0\x07vector3\x03\0\x02\x01r\x04\x01xu\x01yu\x01zu\x01wu\x04\0\x0aqua\
ternion\x03\0\x04\x01r\x09\x03m00u\x03m01u\x03m02u\x03m10u\x03m11u\x03m12u\x03m2\
0u\x03m21u\x03m22u\x04\0\x09matrix3x3\x03\0\x06\x01pu\x01r\x05\x02fxu\x02fyu\x02\
cxu\x02cyu\x04dist\x08\x04\0\x06camera\x03\0\x09\x01r\x02\x08position\x03\x08rot\
ation\x05\x04\0\x04pose\x03\0\x0b\x01r\x04\x04pose\x0c\x0aconfidenceu\x17normali\
zed-corner-erroru\x0dray-distances\x08\x04\0\x14square-pose-estimate\x03\0\x0d\x01\
r\x02\x02ids\x08position\x03\x04\0\x08landmark\x03\0\x0f\x01r\x02\x02ids\x08posi\
tion\x01\x04\0\x14landmark-observation\x03\0\x11\x01m\x03\x04epnp\x09iterative\x05\
sqpnp\x04\0\x10solve-pnp-method\x03\0\x13\x01m\x03\x13insufficient-points\x0dsol\
ver-failed\x11mismatched-counts\x04\0\x09pnp-error\x03\0\x15\x03\0\x14auki:pnp/t\
ypes@0.2.0\x05\0\x02\x03\0\0\x08landmark\x02\x03\0\0\x14landmark-observation\x02\
\x03\0\0\x06camera\x02\x03\0\0\x04pose\x02\x03\0\0\x10solve-pnp-method\x02\x03\0\
\0\x09pnp-error\x02\x03\0\0\x07vector2\x02\x03\0\0\x14square-pose-estimate\x01B\x1c\
\x02\x03\x02\x01\x01\x04\0\x08landmark\x03\0\0\x02\x03\x02\x01\x02\x04\0\x14land\
mark-observation\x03\0\x02\x02\x03\x02\x01\x03\x04\0\x06camera\x03\0\x04\x02\x03\
\x02\x01\x04\x04\0\x04pose\x03\0\x06\x02\x03\x02\x01\x05\x04\0\x10solve-pnp-meth\
od\x03\0\x08\x02\x03\x02\x01\x06\x04\0\x09pnp-error\x03\0\x0a\x02\x03\x02\x01\x07\
\x04\0\x07vector2\x03\0\x0c\x02\x03\x02\x01\x08\x04\0\x14square-pose-estimate\x03\
\0\x0e\x01p\x01\x01p\x03\x01j\x01\x07\x01\x0b\x01@\x04\x09landmarks\x10\x0cobser\
vations\x11\x06camera\x05\x06method\x09\0\x12\x04\0\x09solve-pnp\x01\x13\x04\0\x15\
solve-pnp-camera-pose\x01\x13\x01@\x01\x04pose\x07\0\x07\x04\0\x1fcamera-pose-fr\
om-solve-pnp-pose\x01\x14\x01p\x0d\x01j\x01\x0f\x01\x0b\x01@\x03\x06pixels\x15\x0d\
physical-sizeu\x06camera\x05\0\x16\x04\0\x20estimate-square-pose-from-pixels\x01\
\x17\x04\0\x15auki:pnp/solver@0.2.0\x05\x09\x04\0\x12auki:pnp/pnp@0.2.0\x04\0\x0b\
\x09\x01\0\x03pnp\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-compone\
nt\x070.247.0\x10wit-bindgen-rust\x060.57.1";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
